[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

# SEO routes with prerender bypass
[[redirects]]
  from = "/slownik-erp/*"
  to = "/seo/slownik-erp/:splat/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/firmy-it"
  to = "/seo/firmy-it/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/partnerzy"
  to = "/seo/partnerzy/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/systemy-erp"
  to = "/seo/systemy-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/kalkulator"
  to = "/seo/kalkulator/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/porownaj-systemy-erp"
  to = "/seo/porownaj-systemy-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
