[build]
  command = "npm run build && cp -r public/seo dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

# Dictionary term SEO pages (for bots)
[[redirects]]
  from = "/slownik-erp/*"
  to = "/seo/slownik-erp/:splat"
  status = 200
  force = true
  conditions = {Bot = true}

# Dictionary term pages (for users)
[[redirects]]
  from = "/slownik-erp/*"
  to = "/index.html"
  status = 200
  force = true

# Dictionary index page
[[redirects]]
  from = "/slownik-erp"
  to = "/index.html"
  status = 200

# Companies index page
[[redirects]]
  from = "/firmy-it"
  to = "/index.html"
  status = 200

# Partners page
[[redirects]]
  from = "/partnerzy"
  to = "/index.html"
  status = 200

# Systems page
[[redirects]]
  from = "/systemy-erp"
  to = "/index.html"
  status = 200

# Calculator page
[[redirects]]
  from = "/kalkulator"
  to = "/index.html"
  status = 200

# Compare page
[[redirects]]
  from = "/porownaj-systemy-erp"
  to = "/index.html"
  status = 200

# Default SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
