[build]
  command = "npm run build && cp -r public/seo dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
