[build]
  command = "npm run build && cp -r public/seo dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

# SEO pages for search engines
[[redirects]]
  from = "/slownik-erp/*"
  to = "/seo/slownik-erp/:splat/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

# Dictionary pages for users
[[redirects]]
  from = "/slownik-erp/*"
  to = "/index.html"
  status = 200

# Dictionary index page
[[redirects]]
  from = "/slownik-erp"
  to = "/seo/slownik-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/slownik-erp"
  to = "/index.html"
  status = 200

# Companies index page
[[redirects]]
  from = "/firmy-it"
  to = "/seo/firmy-it/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/firmy-it"
  to = "/index.html"
  status = 200

# Partners page
[[redirects]]
  from = "/partnerzy"
  to = "/seo/partnerzy/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/partnerzy"
  to = "/index.html"
  status = 200

# Systems page
[[redirects]]
  from = "/systemy-erp"
  to = "/seo/systemy-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/systemy-erp"
  to = "/index.html"
  status = 200

# Calculator page
[[redirects]]
  from = "/kalkulator"
  to = "/seo/kalkulator/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/kalkulator"
  to = "/index.html"
  status = 200

# Compare page
[[redirects]]
  from = "/porownaj-systemy-erp"
  to = "/seo/porownaj-systemy-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/porownaj-systemy-erp"
  to = "/index.html"
  status = 200

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
