[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

# First, handle SEO pages
[[redirects]]
  from = "/slownik-erp/*/index.html"
  to = "/seo/slownik-erp/:splat/index.html"
  status = 200

[[redirects]]
  from = "/slownik-erp/index.html"
  to = "/seo/slownik-erp/index.html"
  status = 200

[[redirects]]
  from = "/systemy-erp/index.html"
  to = "/seo/systemy-erp/index.html"
  status = 200

[[redirects]]
  from = "/partnerzy/index.html"
  to = "/seo/partnerzy/index.html"
  status = 200

[[redirects]]
  from = "/koszt-wdrozenia-erp/index.html"
  to = "/seo/koszt-wdrozenia-erp/index.html"
  status = 200

# Then, handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Finally, handle all other routes with SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
