[build]
  command = "npm run build && rm -rf dist/slownik-erp && cp -r public/seo dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

# Legacy dictionary term redirects
[[redirects]]
  from = "/slownik-erp/319-gospodarka-remontowa.html"
  to = "/slownik-erp/gospodarka-remontowa"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

# Dictionary pages
[[redirects]]
  from = "/slownik-erp/*"
  to = "/index.html"
  status = 200

# SEO pages
[[redirects]]
  from = "/.well-known/seo/*"
  to = "/seo/:splat"
  status = 200

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
