[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  path = "/*"
  function = "bot-detection"

# Dictionary term SEO pages (for bots)
[[redirects]]
  from = "/slownik-erp/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Bot = false}

# Dictionary term pages (for users)
[[redirects]]
  from = "/slownik-erp/*"
  to = "/seo/slownik-erp/:splat/index.html"
  status = 200
  force = true
  conditions = {Bot = true}

# Default SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
